In [2]:
!apt-get install -y fonts-nanum > /dev/null
!fc-cache -fv > /dev/null
!rm -rf ~/.cache/matplotlib > /dev/null
# 런타임 다시시작

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib

In [2]:
#그래프에서 마이너스 기호가 표시되게 하는 설정입니다.
plt.rc('font', family='NanumBarunGothic')
matplotlib.rcParams['axes.unicode_minus'] = False

In [3]:
from google.colab import drive
drive.mount('/content/mnt')

Mounted at /content/mnt

In [4]:
filepath = '/content/mnt/MyDrive/proj1_1조/data/기상청/'

In [5]:
lun_df = pd.read_csv(filepath+'일별_점심시간_0409.csv')
eve_df = pd.read_csv(filepath+'일별_저녁시간_0409.csv')

In [6]:
lun_df.describe()

              체감온도         불쾌지수           우산
count  1894.000000  1894.000000  1894.000000
mean     19.134002    61.480993     0.102957
std       9.499848    11.939512     0.303983
min      -6.600000    35.000000     0.000000
25%      11.000000    51.000000     0.000000
50%      19.850000    62.000000     0.000000
75%      27.100000    71.000000     0.000000
max      38.100000    84.000000     1.000000

In [7]:
eve_df.describe()

              체감온도         불쾌지수           우산
count  1894.000000  1894.000000  1894.000000
mean     19.134002    61.480993     0.102957
std       9.499848    11.939512     0.303983
min      -6.600000    35.000000     0.000000
25%      11.000000    51.000000     0.000000
50%      19.850000    62.000000     0.000000
75%      27.100000    71.000000     0.000000
max      38.100000    84.000000     1.000000

## 불쾌지수
80이상 : 매우높음 - 전원 불쾌감

80~75 : 높음 - 불쾌감을 나타내기 시작

75~68 : 보통 - 50%정도 불쾌감을 느낌

68미만 : 낮음 - 전원 쾌적함을 느낌

In [ ]:
# 불쾌지수 분류 함수

In [8]:
def make_discomfort(df):
  df['쾌적'] = df['불쾌지수'].apply(lambda x: 1 if  (x < 75) else 0)
  df['불쾌'] = df['불쾌지수'].apply(lambda x: 1 if (75 <= x) else 0)

  return df

In [9]:
new_lun_df = make_discomfort(lun_df)
new_eve_df = make_discomfort(eve_df)

In [10]:
new_lun_df.head(600).tail(5)

             날짜  체감온도  불쾌지수  우산  쾌적  불쾌
595  2017-09-18  28.3    72   0   1   0
596  2017-09-19  28.4    73   0   1   0
597  2017-09-20  26.5    70   0   1   0
598  2017-09-21  25.9    69   0   1   0
599  2017-09-22  26.4    70   0   1   0

## 폭염

- 체감온도 33도 이상

In [12]:
def make_temper(df):
  # df['폭염'] = df['체감온도'].apply(lambda x: 1 if x >= 33.0 else 0)
  # df['한파'] = df['체감온도'].apply(lambda x: 1 if x < (-10.0) # 한파에 대해서
  df['저온'] = df['체감온도'].apply(lambda x: 1 if x < 0.0 else 0)
  df['중온'] = df['체감온도'].apply(lambda x: 1 if (0.0 <= x) & (x < 20.0) else 0)
  df['고온'] = df['체감온도'].apply(lambda x: 1 if 20.0 < x else 0)
  return df

In [13]:
new_lun_df = make_temper(new_lun_df)
new_eve_df = make_temper(new_eve_df)

In [14]:
new_lun_df.head(600).tail()

             날짜  체감온도  불쾌지수  우산  쾌적  불쾌  저온  중온  고온
595  2017-09-18  28.3    72   0   1   0   0   0   1
596  2017-09-19  28.4    73   0   1   0   0   0   1
597  2017-09-20  26.5    70   0   1   0   0   0   1
598  2017-09-21  25.9    69   0   1   0   0   0   1
599  2017-09-22  26.4    70   0   1   0   0   0   1

In [15]:
new_eve_df.head(570).tail()

             날짜  체감온도  불쾌지수  우산  쾌적  불쾌  저온  중온  고온
565  2017-08-19  29.2    77   1   0   1   0   0   1
566  2017-08-20  30.1    78   0   0   1   0   0   1
567  2017-08-21  30.1    79   1   0   1   0   0   1
568  2017-08-22  29.6    79   1   0   1   0   0   1
569  2017-08-23  34.2    82   0   0   1   0   0   1

In [16]:
lunch = new_lun_df.drop(['체감온도', '불쾌지수'], axis=1)
dinner = new_lun_df.drop(['체감온도', '불쾌지수'], axis=1)

In [17]:
lunch.rename(columns={'날짜':'일자'}, inplace=True)
dinner.rename(columns={'날짜':'일자'}, inplace=True)

In [18]:
lunch.to_csv(filepath+'lunch.csv', index=False)
dinner.to_csv(filepath+'dinner.csv', index=False)